
#ifndef MENUMAKER_MENU_H
#define MENUMAKER_MENU_H

#include "MenuMaker.h"

#define MENUMAKER_ID_entry_4 0
#define MENUMAKER_ID_lists 1
#define MENUMAKER_ID_action_4 2
#define MENUMAKER_ID_actions 3
#define MENUMAKER_ID_entry_5 4
#define MENUMAKER_ID_action_2 5
#define MENUMAKER_ID_entry_3 6
#define MENUMAKER_ID_edits 7
#define MENUMAKER_ID_action_3 8
#define MENUMAKER_ID_entry_2 9
#define MENUMAKER_ID_subs 10
#define MENUMAKER_ID_entry_1 11
#define MENUMAKER_ID_main 12
#define MENUMAKER_ID_single 13
#define MENUMAKER_ID_edit_1 14
#define MENUMAKER_ID_entry_6 15
#define MENUMAKER_ID_multi 16
#define MENUMAKER_ID_action_1 17
const char *MENUMAKER_ID_STRING_0 = "Single select";
const char *MENUMAKER_ID_STRING_1 = "Entry 4";
const char *MENUMAKER_ID_STRING_2 = "Entry 2";
const char *MENUMAKER_ID_STRING_3 = "Entry 6";
const char *MENUMAKER_ID_STRING_4 = "Entry 5";
const char *MENUMAKER_ID_STRING_5 = "Entry 1";
const char *MENUMAKER_ID_STRING_6 = "Entry 3";
const char *MENUMAKER_ID_STRING_7 = "Actions";
const char *MENUMAKER_ID_STRING_8 = "Action 4";
const char *MENUMAKER_ID_STRING_9 = "Action 2";
const char *MENUMAKER_ID_STRING_10 = "Action 3";
const char *MENUMAKER_ID_STRING_11 = "Action 1";
const char *MENUMAKER_ID_STRING_12 = "Lists";
const char *MENUMAKER_ID_STRING_13 = "Multiple select";
const char *MENUMAKER_ID_STRING_14 = "Submenus";
const char *MENUMAKER_ID_STRING_15 = "Same again 3";
const char *MENUMAKER_ID_STRING_16 = "Edit Inputs";
const char *MENUMAKER_ID_STRING_17 = "Integer";
const char *MENUMAKER_ID_STRING_18 = "Example";
MenuMakerImpl::MenuMakerImpl() : MenuMaker() {
	createMenu(MENUMAKER_ID_single, MENUMAKER_ID_STRING_0, MENUMAKER_TYPE_SELECT_SINGLE)
		->addEntry(MENUMAKER_ID_entry_1, MENUMAKER_ID_STRING_5,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_2, MENUMAKER_ID_STRING_2,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_3, MENUMAKER_ID_STRING_6,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_4, MENUMAKER_ID_STRING_1,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_5, MENUMAKER_ID_STRING_4,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_6, MENUMAKER_ID_STRING_3,MENUMAKER_TYPE_DEFAULT);

	createMenu(MENUMAKER_ID_actions, MENUMAKER_ID_STRING_7, MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_action_1, MENUMAKER_ID_STRING_11,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_action_2, MENUMAKER_ID_STRING_9,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_action_3, MENUMAKER_ID_STRING_10,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_action_4, MENUMAKER_ID_STRING_8,MENUMAKER_TYPE_DEFAULT);

	createMenu(MENUMAKER_ID_lists, MENUMAKER_ID_STRING_12, MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_actions, MENUMAKER_ID_STRING_7,MENUMAKER_TYPE_SUBMENU)
		->addEntry(MENUMAKER_ID_single, MENUMAKER_ID_STRING_0,MENUMAKER_TYPE_SUBMENU)
		->addEntry(MENUMAKER_ID_multi, MENUMAKER_ID_STRING_13,MENUMAKER_TYPE_SUBMENU);

	createMenu(MENUMAKER_ID_subs, MENUMAKER_ID_STRING_14, MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_subs, MENUMAKER_ID_STRING_15,MENUMAKER_TYPE_SUBMENU);

	createMenu(MENUMAKER_ID_multi, MENUMAKER_ID_STRING_13, MENUMAKER_TYPE_SELECT_MULTI)
		->addEntry(MENUMAKER_ID_entry_1, MENUMAKER_ID_STRING_5,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_2, MENUMAKER_ID_STRING_2,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_3, MENUMAKER_ID_STRING_6,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_4, MENUMAKER_ID_STRING_1,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_5, MENUMAKER_ID_STRING_4,MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_entry_6, MENUMAKER_ID_STRING_3,MENUMAKER_TYPE_DEFAULT);

	createMenu(MENUMAKER_ID_edits, MENUMAKER_ID_STRING_16, MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_edit_1, MENUMAKER_ID_STRING_17,MENUMAKER_TYPE_DEFAULT);

	createMenu(MENUMAKER_ID_main, MENUMAKER_ID_STRING_18, MENUMAKER_TYPE_DEFAULT)
		->addEntry(MENUMAKER_ID_subs, MENUMAKER_ID_STRING_14,MENUMAKER_TYPE_SUBMENU)
		->addEntry(MENUMAKER_ID_lists, MENUMAKER_ID_STRING_12,MENUMAKER_TYPE_SUBMENU)
		->addEntry(MENUMAKER_ID_edits, MENUMAKER_ID_STRING_16,MENUMAKER_TYPE_SUBMENU);

}

#endif // MENUMAKER_MENU_H
